Working on desktop version
shimels1/portfolio_microverse pull request #7
Opened 2023-07-20 17:29 UTC by shimels1

-  Adding media query.
- Make changes to style and index.html files.

2023-07-20 18:38 UTC, Alusp requested changes
Hi @shimels1, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![close](https://media.giphy.com/media/nJKDTpuxnZE7fb6Z1b/giphy.gif)

 ## Highlights

- [ ] Linters set-up ✔️
- [ ] Commit messages descriptive ✔️
- [ ] Professional GitHub Flow used ✔️
- [ ] Profesional PR Summary ✔️
- [ ] Use media queries :heavy_check_mark: 



## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @shimels1 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-20 18:38 UTC, Alusp commented on css/style.css
> +  }
- [ ] You have done great job so far, :clap: , However, as part of the project requirement that says: `You must replicate the design as much as possible (e.g., font, colors, images, text, margins)` using this [template](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?type=design&node-id=0-1&mode=design&t=g3dMloiCFcFPsC5J-0). matching your design to the given design requirements enhances the chances of creating a successful and well-rounded design solution that meets the needs of users, complies with regulations, and performs effectively and efficiently. :slightly_smiling_face: 

The example below shows the difference between yours and the accepted one: :arrow_down: 

 <table>
    <tr>
      <td>Yours </td>
      <td>Figma</td>
    </tr>
    <tr>
      <td>

 
![FigStudentHome](https://github.com/shimels1/portfolio_microverse/assets/43528594/8a6ec3db-6b52-4e9e-a309-da9246f224f2)

 
</td>
      <td>

![StudentHome](https://github.com/shimels1/portfolio_microverse/assets/43528594/2f9d5c45-02b4-4fa2-af00-2755c130670f)

</td>
    </tr>
  </table>

2023-07-21 12:00 UTC, franclobo approved these changes
Hi @shimels1, 

# STATUS: APPROVED 😃 

![git-merge](https://github.com/shimels1/portfolio_microverse/assets/58642949/24efaa38-191f-4002-83b1-9fde55b09405)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- No linter errors ✔️ 
- Descriptive PR ✔️ 
- Correct Github flow ✔️ 
- Correct use of background-image with CSS ✔️ 

## Optional suggestions

- **[OPTIONAL]** The images on the cards are differents for each one, please fix them to be similar to the Figma template 👇🏽 

| Figma template | Yoyr design |
|---|---|
| ![image](https://github.com/shimels1/portfolio_microverse/assets/58642949/cb7b1101-8c86-4a33-9e64-c5a2dd178d2f) | ![image](https://github.com/shimels1/portfolio_microverse/assets/58642949/d5e4307a-e6cc-46dd-877b-7bdcc4c838a2) |



_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-21 13:44 UTC, merged

2023-07-24 10:50 UTC, TedLivist reviewed
## STATUS: INVALID CODE REVIEW REQUEST 🛑 🛑

Hi @shimels1,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

### You have submitted a PR that is not related to the application deploy project. Kindly follow the project guideline and submit the new PR for the application deploy project.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._